//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHBWin_Neu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetOptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BetOptions()
        {
            this.Placement = new HashSet<Placement>();
        }
    
        public int OptionsID { get; set; }
        public Nullable<int> BetID { get; set; }
        public string Title { get; set; }
        public string Descpription { get; set; }
    
        public virtual Bet Bet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Placement> Placement { get; set; }
    }
}
