//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHBWin_Neu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Reward { get; set; }
        public Nullable<int> ExpPoints { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
