//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHBWin_Neu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dhbwinEntities : DbContext
    {
        public dhbwinEntities()
            : base("name=dhbwinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievement { get; set; }
        public virtual DbSet<Bet> Bet { get; set; }
        public virtual DbSet<BetOptions> BetOptions { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<Placement> Placement { get; set; }
        public virtual DbSet<PLZ> PLZ { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
