//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHBWin_Neu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placement
    {
        public int PlacementID { get; set; }
        public int BetID_fk { get; set; }
        public int UID_fk { get; set; }
        public Nullable<int> OptionID_fk { get; set; }
    
        public virtual Bet Bet { get; set; }
        public virtual BetOptions BetOptions { get; set; }
        public virtual User User { get; set; }
    }
}
